/**
 * Localization table — Delta's `babel`. Auto-generated UI text (environment
 * labels, caption prefixes, structural words) is keyed here by language. The
 * emitter resolves the document's `lang`, inlines `stringsFor(lang)` as the
 * `#delta-i18n` data-island, and the runtime looks each key up via `t()`.
 *
 * Adding a translatable string = a key in every block. Adding a language = a
 * new block; `en` is the base every other language falls back to (`stringsFor`).
 */

const DEFAULT_LANG = "en";

export const STRINGS: Record<string, Record<string, string>> = {
  en: {
    // environment labels (one per ENVIRONMENT_TAGS entry)
    theorem: "Theorem",
    proposition: "Proposition",
    lemma: "Lemma",
    corollary: "Corollary",
    conjecture: "Conjecture",
    definition: "Definition",
    example: "Example",
    claim: "Claim",
    observation: "Observation",
    exercise: "Exercise",
    problem: "Problem",
    proof: "Proof",
    solution: "Solution",
    remark: "Remark",
    section: "Section",
    subsection: "Subsection",
    subsubsection: "Subsubsection",
    equations: "Equations",
    equation: "Equation",
    figure: "Figure",
    interactive: "Interactive",
    table: "Table",
    video: "Video",
    audio: "Audio",
    contents: "Contents",
    hint: "Hint",
    references: "References",
    close: "Close",
    code: "Code",
    copy: "Copy",
    copied: "Copied",
    prevSlide: "Previous slide",
    nextSlide: "Next slide",
    // front matter (abstract + labeled metadata)
    abstract: "Abstract",
    keywords: "Keywords",
    msc: "Mathematics Subject Classification",
    received: "Received",
    revised: "Revised",
    accepted: "Accepted",
    submitted: "Submitted",
    date: "Date",
    acknowledgements: "Acknowledgements",
    funding: "Funding",
    // collaboration (comment / todo / change / status / review panel)
    comment: "Comment",
    todo: "Task",
    tasks: "Tasks",
    change: "Change",
    reply: "Reply",
    open: "Open",
    resolved: "Resolved",
    doing: "In progress",
    done: "Done",
    draft: "Draft",
    sketch: "Sketch",
    review: "In review",
    verified: "Verified",
    human: "human",
    agent: "agent",
    insert: "Inserted",
    delete: "Deleted",
    replace: "Replaced",
    pending: "Pending",
    reviewPanel: "Review",
    annotations: "Annotations",
    changes: "Changes",
    markup: "Markup",
    final: "Final",
    original: "Original",
    copyText: "Copy as text",
    openComments: "open comments",
    openTasks: "open tasks",
    pendingChanges: "pending changes",
    blocks: "blocks",
    all: "All",
    nothingToReview: "Nothing to review",
    high: "High",
    normal: "Normal",
    low: "Low",
    due: "Due",
    by: "by",
    for: "for",
    verifiedBy: "verified by",
    note: "Note",
    jumpTo: "Go to",
  },
  pt: {
    theorem: "Teorema",
    proposition: "Proposição",
    lemma: "Lema",
    corollary: "Corolário",
    conjecture: "Conjectura",
    definition: "Definição",
    example: "Exemplo",
    claim: "Afirmação",
    observation: "Observação",
    exercise: "Exercício",
    problem: "Problema",
    proof: "Demonstração",
    solution: "Solução",
    remark: "Comentário",
    section: "Seção",
    subsection: "Subseção",
    subsubsection: "Subsubseção",
    equation: "Equação",
    equations: "Equações",
    figure: "Figura",
    interactive: "Interativo",
    table: "Tabela",
    video: "Vídeo",
    audio: "Áudio",
    contents: "Sumário",
    hint: "Dica",
    references: "Referências",
    close: "Fechar",
    code: "Código",
    copy: "Copiar",
    copied: "Copiado",
    prevSlide: "Slide anterior",
    nextSlide: "Próximo slide",
    // front matter (abstract + labeled metadata)
    abstract: "Resumo",
    keywords: "Palavras-chave",
    msc: "Classificação por Assunto (MSC)",
    received: "Recebido",
    revised: "Revisado",
    accepted: "Aceito",
    submitted: "Submetido",
    date: "Data",
    acknowledgements: "Agradecimentos",
    funding: "Financiamento",
    // colaboração (comment / todo / change / status / painel de revisão).
    // `remark` já é "Comentário", e o rótulo de um <ref> é t(tag) + número — por isso
    // <comment> vira "Anotação", para "Anotação 3" não se confundir com "Comentário 3".
    comment: "Anotação",
    todo: "Tarefa",
    tasks: "Tarefas",
    change: "Alteração",
    reply: "Resposta",
    open: "Aberta",
    resolved: "Resolvida",
    doing: "Em andamento",
    done: "Concluída",
    draft: "Rascunho",
    sketch: "Esboço",
    review: "Em revisão",
    verified: "Verificado",
    human: "humano",
    agent: "agente",
    insert: "Inserido",
    delete: "Removido",
    replace: "Substituído",
    pending: "Pendente",
    reviewPanel: "Revisão",
    annotations: "Anotações",
    changes: "Alterações",
    markup: "Marcação",
    final: "Final",
    original: "Original",
    copyText: "Copiar como texto",
    openComments: "anotações abertas",
    openTasks: "tarefas abertas",
    pendingChanges: "alterações pendentes",
    blocks: "blocos",
    all: "Todos",
    nothingToReview: "Nada a revisar",
    high: "Alta",
    normal: "Normal",
    low: "Baixa",
    due: "Prazo",
    by: "por",
    for: "para",
    verifiedBy: "verificado por",
    note: "Nota",
    jumpTo: "Ir para",
  },
};

/** Normalize a `lang` to a key present in STRINGS: `pt-BR` → `pt`, unknown → `en`. */
export function resolveLang(lang?: string): string {
  if (!lang) return DEFAULT_LANG;
  const lower = lang.toLowerCase();
  if (STRINGS[lower]) return lower;
  const base = lower.split("-")[0];
  if (STRINGS[base]) return base;
  return DEFAULT_LANG;
}

/** Merged string set for a resolved language with `en` base overlaid by the language,
 *  so any key a language omits falls back to English. Pass a `resolveLang` result. */
export function stringsFor(lang: string): Record<string, string> {
  return { ...STRINGS[DEFAULT_LANG], ...(STRINGS[lang] ?? {}) };
}
