import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { build } from "esbuild";

const require = createRequire(import.meta.url);

/**
 * Two-step build. The `assets` step bundles the browser runtime into an IIFE
 * string and, together with the stylesheets, writes src/generated/assets.ts —
 * the emitter imports it, so this must run before typecheck/test/compile (the
 * pre-scripts in package.json take care of that). The default mode also
 * bundles the CLI to dist/cli.js.
 */

const STYLES = "src/styles";

/** Newsreader — the design's primary serif (--delta-serif lists it first) —
 *  inlined as @font-face with the variable woff2 (weight + optical size)
 *  embedded as a data: URI, so documents render in it offline instead of
 *  falling back to a system serif. Unlayered, so it applies document-wide; the
 *  output still references nothing external (guarded by test/emit.test.ts). */
function fontFaces(): string {
  const dir = join(dirname(require.resolve("@fontsource-variable/newsreader/package.json")), "files");
  const face = (style: string, file: string) => {
    const data = readFileSync(join(dir, file)).toString("base64");
    return (
      `@font-face{font-family:"Newsreader";font-style:${style};font-weight:200 800;` +
      `font-display:swap;src:url(data:font/woff2;base64,${data}) format("woff2");}`
    );
  };
  return [
    face("normal", "newsreader-latin-standard-normal.woff2"),
    face("italic", "newsreader-latin-standard-italic.woff2"),
  ].join("\n");
}

/** Inlined @font-face + base.css + every components/*.css, concatenated (fonts
 *  and base first; the @layer declaration at the top of base.css fixes cascade
 *  order document-wide — @font-face is unlayered and unaffected). */
function coreCss(): string {
  const base = readFileSync(join(STYLES, "base.css"), "utf8");
  const components = readdirSync(join(STYLES, "components"))
    .filter((f) => f.endsWith(".css"))
    .sort()
    .map((f) => readFileSync(join(STYLES, "components", f), "utf8"));
  return [fontFaces(), base, ...components].join("\n");
}

/** themes/<type>.css → { [type]: css }; emit.ts picks one by <document type>. */
function themeCss(): Record<string, string> {
  const dir = join(STYLES, "themes");
  const themes: Record<string, string> = {};
  for (const f of readdirSync(dir)) {
    if (f.endsWith(".css")) themes[f.replace(/\.css$/, "")] = readFileSync(join(dir, f), "utf8");
  }
  return themes;
}

async function buildAssets(): Promise<void> {
  const result = await build({
    entryPoints: ["src/runtime/index.ts"],
    bundle: true,
    format: "iife",
    target: "es2020",
    minify: true,
    write: false,
  });
  const runtime = result.outputFiles[0].text.trim();
  mkdirSync("src/generated", { recursive: true });
  writeFileSync(
    "src/generated/assets.ts",
    "// Generated by scripts/build.ts — do not edit, do not commit.\n" +
      `export const RUNTIME_JS = ${JSON.stringify(runtime)};\n` +
      `export const CORE_CSS = ${JSON.stringify(coreCss())};\n` +
      `export const THEMES: Record<string, string> = ${JSON.stringify(themeCss())};\n`,
  );
}

async function buildCli(): Promise<void> {
  await build({
    entryPoints: ["src/cli.ts"],
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    packages: "external",
    outfile: "dist/cli.js",
  });
}

await buildAssets();
if (process.argv[2] !== "assets") await buildCli();
